"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 5.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path
import os
from decouple import config

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# ============================================================================
# Security Settings
# إعدادات الأمان
# ============================================================================

# SECURITY WARNING: keep the secret key used in production secret!
# تحذير أمني: احتفظ بمفتاح Django السري سراً في الإنتاج!

# Django Secret Key
# مفتاح Django السري - مطلوب في جميع البيئات
# يجب أن يكون قوياً وفريداً - لا تشاركه أبداً
# Generate: python -c "from django.core.management.utils import get_random_secret_key; print(get_random_secret_key())"
SECRET_KEY = config('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
# تحذير أمني: لا تشغل DEBUG=True في الإنتاج!

# Debug Mode
# وضع التطوير - يعرض معلومات خطأ مفصلة
# في الإنتاج: يجب أن يكون False دائماً
# في التطوير: يمكن أن يكون True
DEBUG = config('DEBUG', default=False, cast=bool)

# Allowed Hosts
# القائمة المسموح لها بالوصول للتطبيق
# في الإنتاج: يجب تحديد domain names الفعلية
# في التطوير: localhost, 127.0.0.1
ALLOWED_HOSTS = config('ALLOWED_HOSTS', default='localhost,127.0.0.1').split(',')


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    # Third party
    "rest_framework",
    "corsheaders",
    "django_filters",
    "drf_spectacular",
    # Local apps
    "users",          # User management app - must be before other apps that reference User
    "vendors",        # Vendor management
    "products",       # Product catalog
    "orders",         # Order management
    "promotions",     # Promotions (Banners, Stories, Coupons)
    "settings_app",   # Site settings and configuration
    "admin_api",      # Admin Dashboard API - إدارة لوحة التحكم
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    # Custom Middleware
    # Middleware مخصص
    "core.middleware.RequestLoggingMiddleware",  # Request logging for API monitoring
    "core.middleware.ErrorHandlingMiddleware",  # Standardized error handling
]

ROOT_URLCONF = "core.urls"

# ============================================================================
# Custom User Model Configuration
# إعدادات نموذج المستخدم المخصص
# ============================================================================
# Tell Django to use our custom User model instead of the default one
# أخبر Django باستخدام نموذج المستخدم المخصص بدلاً من الافتراضي
# IMPORTANT: This must be set before creating any migrations!
# مهم: يجب تعيين هذا قبل إنشاء أي migrations!
AUTH_USER_MODEL = 'users.User'

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "core.wsgi.application"


# ============================================================================
# Database Configuration
# إعدادات قاعدة البيانات PostgreSQL
# ============================================================================
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

import dj_database_url

# Database URL (Priority 1: For Docker/Production)
# رابط قاعدة البيانات (الأولوية الأولى: لـ Docker/الإنتاج)
# Format: postgresql://user:password@host:port/dbname
database_url = config('DATABASE_URL', default=None)

if database_url:
    # إذا كان DATABASE_URL موجوداً، استخدمه (Docker/Production)
    # If DATABASE_URL exists, use it (Docker/Production)
    DATABASES = {
        "default": dj_database_url.parse(database_url)
    }
else:
    # Individual Database Settings (Priority 2: For Local Development)
    # إعدادات قاعدة البيانات الفردية (الأولوية الثانية: للتطوير المحلي)
    # في الإنتاج: يجب استخدام DATABASE_URL بدلاً من هذه القيم
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.postgresql",
            "NAME": config('DB_NAME'),  # مطلوب - اسم قاعدة البيانات
            "USER": config('DB_USER'),  # مطلوب - مستخدم قاعدة البيانات
            "PASSWORD": config('DB_PASSWORD'),  # مطلوب - كلمة مرور قوية
            "HOST": config('DB_HOST', default='localhost'),  # افتراضي: localhost
            "PORT": config('DB_PORT', default='5432'),  # افتراضي: 5432
        }
    }

# ============================================================================
# Production Security Validation
# التحقق من الأمان في الإنتاج
# ============================================================================
if not DEBUG:
    # في الإنتاج، تأكد من أن SECRET_KEY قوي
    # In production, ensure SECRET_KEY is strong
    if SECRET_KEY.startswith('django-insecure-'):
        raise ValueError(
            "SECURITY ERROR: You must set a strong SECRET_KEY in production! "
            "Do not use the default insecure key."
        )
    
    # في الإنتاج، تأكد من أن ALLOWED_HOSTS محددة
    # In production, ensure ALLOWED_HOSTS is specified
    if 'localhost' in ALLOWED_HOSTS or '127.0.0.1' in ALLOWED_HOSTS:
        import warnings
        warnings.warn(
            "SECURITY WARNING: localhost/127.0.0.1 in ALLOWED_HOSTS in production! "
            "This is insecure. Use your actual domain names.",
            UserWarning
        )


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "Asia/Damascus"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = "static/"
STATIC_ROOT = BASE_DIR / "staticfiles"

MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

# Default primary key field type
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# ============================================================================
# REST Framework Configuration
# إعدادات Django REST Framework للـ API
# ============================================================================
REST_FRAMEWORK = {
    # Schema Class for API Documentation
    # كلاس Schema لتوثيق الـ API تلقائياً (drf-spectacular)
    # يولد OpenAPI schema تلقائياً من serializers و views
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
    
    # Filter Backends
    # محركات الفلترة للبحث والتصفية في الـ API
    # django_filters: يسمح بالفلترة حسب الحقول (vendor, color, size, etc.)
    "DEFAULT_FILTER_BACKENDS": ["django_filters.rest_framework.DjangoFilterBackend"],
    
    # Pagination Configuration
    # إعدادات التقسيم للصفحات
    # StandardResultsSetPagination: تقسيم موحد يعمل للويب والموبايل
    # StandardResultsSetPagination: unified pagination that works for both web and mobile
    "DEFAULT_PAGINATION_CLASS": "core.pagination.StandardResultsSetPagination",
    
    # Page Size: عدد العناصر في كل صفحة
    # 24 منتج لكل صفحة (مناسب لعرض grid من المنتجات)
    # 24 products per page (suitable for product grid display)
    "PAGE_SIZE": 24,
    
    # Authentication Classes
    # فئات المصادقة - JWT Authentication
    # SimpleJWT: يستخدم JSON Web Tokens للمصادقة بدون حالة (stateless)
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework_simplejwt.authentication.JWTAuthentication",
        "rest_framework.authentication.SessionAuthentication",  # للـ Django Admin
    ],
    
    # Permission Classes
    # فئات الصلاحيات - افتراضياً: يجب أن يكون المستخدم مسجلاً
    # IsAuthenticated: يسمح فقط للمستخدمين المسجلين
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticated",
    ],
    
    # Throttling (Rate Limiting)
    # تحديد معدل الطلبات - حماية من الإفراط في الاستخدام
    "DEFAULT_THROTTLE_CLASSES": [
        "rest_framework.throttling.AnonRateThrottle",  # للمستخدمين غير المسجلين
        "rest_framework.throttling.UserRateThrottle",  # للمستخدمين المسجلين
    ],
    "DEFAULT_THROTTLE_RATES": {
        # In development: higher limits for easier testing
        # في التطوير: حدود أعلى لتسهيل الاختبار
        # In production: stricter limits for security
        # في الإنتاج: حدود أكثر صرامة للأمان
        "anon": "100/hour" if not DEBUG else "1000/hour",      # 100 طلب في الساعة (1000 في التطوير)
        "user": "1000/hour" if not DEBUG else "10000/hour",    # 1000 طلب في الساعة (10000 في التطوير)
        "admin": "5000/hour" if not DEBUG else "50000/hour",   # 5000 طلب في الساعة للـ admin (50000 في التطوير)
        "login": "5/minute",     # 5 محاولات تسجيل دخول في الدقيقة
        "register": "3/minute",  # 3 محاولات تسجيل في الدقيقة
    },
}

# ============================================================================
# CORS (Cross-Origin Resource Sharing) Settings
# إعدادات CORS للسماح للـ Frontend بالوصول للـ API
# ============================================================================
# CORS_ALLOWED_ORIGINS: قائمة المصادر المسموح لها بالوصول للـ API
# في التطوير: نسمح فقط لـ localhost:3000 (Next.js frontend)
# في الإنتاج: يجب تحديث هذه القائمة لتشمل domain الإنتاج
CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",      # Next.js development server
    "http://127.0.0.1:3000",      # Alternative localhost
    "http://localhost:3001",      # Next.js fallback port
    "http://127.0.0.1:3001",      # Alternative fallback
]


# CORS_ALLOW_CREDENTIALS: السماح بإرسال credentials (cookies, auth headers)
# مهم للـ JWT authentication لاحقاً
CORS_ALLOW_CREDENTIALS = True

# ============================================================================
# drf-spectacular Settings (API Documentation)
# إعدادات drf-spectacular لتوثيق الـ API
# ============================================================================
SPECTACULAR_SETTINGS = {
    # API Title and Version
    # عنوان ونسخة الـ API
    "TITLE": "Trendyol-SY API",
    "DESCRIPTION": "Multi-vendor e-commerce platform API for Syrian market",
    "VERSION": "1.0.0",
    
    # API Server URLs
    # عناوين خوادم الـ API
    "SERVERS": [
        {"url": "http://localhost:8000", "description": "Development server"},
        # {"url": "https://api.trendyol-sy.com", "description": "Production server"},
    ],
    
    # Schema Settings
    # إعدادات Schema
    "SCHEMA_PATH_PREFIX": "/api/",  # Prefix لجميع مسارات الـ API
}

# ============================================================================
# JWT (JSON Web Token) Configuration
# إعدادات JWT للمصادقة
# ============================================================================
from datetime import timedelta

SIMPLE_JWT = {
    # Access Token Lifetime
    # مدة صلاحية Access Token (15 دقيقة)
    # Access Token يستخدم للوصول للـ API
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=15),
    
    # Refresh Token Lifetime
    # مدة صلاحية Refresh Token (7 أيام)
    # Refresh Token يستخدم لتجديد Access Token
    "REFRESH_TOKEN_LIFETIME": timedelta(days=7),
    
    # Rotate Refresh Tokens
    # تدوير Refresh Tokens: عند استخدام refresh token، يتم إنشاء refresh token جديد
    # هذا يحسن الأمان: إذا تم سرقة refresh token، يصبح غير صالح بعد الاستخدام
    "ROTATE_REFRESH_TOKENS": True,
    
    # Blacklist After Rotation
    # إضافة Refresh Token القديم للقائمة السوداء بعد التدوير
    # يمنع استخدام نفس refresh token مرتين
    "BLACKLIST_AFTER_ROTATION": True,
    
    # Update Last Login
    # تحديث last_login عند استخدام token
    "UPDATE_LAST_LOGIN": True,
    
    # Algorithm
    # خوارزمية التوقيع: HS256 (متناظرة - أسرع)
    "ALGORITHM": "HS256",
    
    # Signing Key
    # مفتاح التوقيع: يستخدم SECRET_KEY من Django
    "SIGNING_KEY": SECRET_KEY,
    
    # Token Type
    # نوع Token في الـ header
    "AUTH_HEADER_TYPES": ("Bearer",),
    
    # Auth Header Name
    # اسم الـ header للمصادقة
    "AUTH_HEADER_NAME": "HTTP_AUTHORIZATION",
    
    # User ID Field
    # الحقل المستخدم كـ user identifier في token
    "USER_ID_FIELD": "id",
    "USER_ID_CLAIM": "user_id",
    
    # Token Blacklist
    # استخدام blacklist للـ tokens الملغاة
    # يتطلب تثبيت: pip install django-rest-framework-simplejwt[blacklist]
    # "BLACKLIST_TOKEN_CHECKS": ["rest_framework_simplejwt.token_blacklist.models.BlacklistedToken"],
}

# ============================================================================
# Email Configuration (Gmail SMTP - Free)
# إعدادات البريد الإلكتروني (Gmail SMTP - مجاني)
# ============================================================================
# Email Backend
# محرك البريد الإلكتروني: SMTP
EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"

# SMTP Server Settings
# إعدادات خادم SMTP (Gmail)
EMAIL_HOST = config("EMAIL_HOST", default="smtp.gmail.com")
EMAIL_PORT = config("EMAIL_PORT", default=587, cast=int)
EMAIL_USE_TLS = config("EMAIL_USE_TLS", default=True, cast=bool)

# Email Credentials
# بيانات اعتماد البريد الإلكتروني
# يجب إنشاء App Password من Gmail (ليس كلمة المرور العادية)
# https://myaccount.google.com/apppasswords
EMAIL_HOST_USER = config("EMAIL_HOST_USER", default="")
EMAIL_HOST_PASSWORD = config("EMAIL_HOST_PASSWORD", default="")

# Default From Email
# البريد الإلكتروني الافتراضي للمرسل
DEFAULT_FROM_EMAIL = config("DEFAULT_FROM_EMAIL", default=EMAIL_HOST_USER)
SERVER_EMAIL = DEFAULT_FROM_EMAIL

# Email Subject Prefix
# بادئة موضوع البريد الإلكتروني
EMAIL_SUBJECT_PREFIX = "[Trendyol-SY] "

# ============================================================================
# Site Configuration (for Email Links)
# إعدادات الموقع (لروابط البريد الإلكتروني)
# ============================================================================
# Frontend URL (for email verification links)
# رابط Frontend (لروابط التحقق من البريد الإلكتروني)
FRONTEND_URL = config("FRONTEND_URL", default="http://localhost:3000")
