"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 5.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path
import os
from decouple import config

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# ============================================================================
# Security Settings
# إعدادات الأمان
# ============================================================================

# SECURITY WARNING: keep the secret key used in production secret!
# تحذير أمني: احتفظ بمفتاح Django السري سراً في الإنتاج!

# Django Secret Key
# مفتاح Django السري - مطلوب في جميع البيئات
# يجب أن يكون قوياً وفريداً - لا تشاركه أبداً
# Generate: python -c "from django.core.management.utils import get_random_secret_key; print(get_random_secret_key())"
SECRET_KEY = config('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
# تحذير أمني: لا تشغل DEBUG=True في الإنتاج!

# Debug Mode
# وضع التطوير - يعرض معلومات خطأ مفصلة
# في الإنتاج: يجب أن يكون False دائماً
# في التطوير: يمكن أن يكون True
DEBUG = config('DEBUG', default=False, cast=bool)

# Allowed Hosts
# القائمة المسموح لها بالوصول للتطبيق
# في الإنتاج: يجب تحديد domain names الفعلية
# في التطوير: localhost, 127.0.0.1
ALLOWED_HOSTS = config('ALLOWED_HOSTS', default='localhost,127.0.0.1').split(',')


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.postgres",  # PostgreSQL-specific features (Full-Text Search)
    # Third party
    "rest_framework",
    "corsheaders",
    "django_filters",
    "drf_spectacular",
    # Local apps
    "users",          # User management app - must be before other apps that reference User
    "vendors",        # Vendor management
    "products",       # Product catalog
    "cart",           # Shopping cart management
    "orders",         # Order management
    "promotions",     # Promotions (Banners, Stories, Coupons)
    "settings_app",   # Site settings and configuration
    "notifications",  # Notifications for admin users
    "admin_api",      # Admin Dashboard API - إدارة لوحة التحكم
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.middleware.gzip.GZipMiddleware",  # GZip compression for responses - ضغط الاستجابات
    "django.contrib.sessions.middleware.SessionMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    # Custom Middleware
    # Middleware مخصص
    "core.middleware.RequestLoggingMiddleware",  # Request logging for API monitoring
    "core.middleware.ErrorHandlingMiddleware",  # Standardized error handling
]

ROOT_URLCONF = "core.urls"

# ============================================================================
# Custom User Model Configuration
# إعدادات نموذج المستخدم المخصص
# ============================================================================
# Tell Django to use our custom User model instead of the default one
# أخبر Django باستخدام نموذج المستخدم المخصص بدلاً من الافتراضي
# IMPORTANT: This must be set before creating any migrations!
# مهم: يجب تعيين هذا قبل إنشاء أي migrations!
AUTH_USER_MODEL = 'users.User'

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "core.wsgi.application"


# ============================================================================
# Database Configuration
# إعدادات قاعدة البيانات PostgreSQL
# ============================================================================
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

import dj_database_url

# Database URL (Priority 1: For Docker/Production)
# رابط قاعدة البيانات (الأولوية الأولى: لـ Docker/الإنتاج)
# Format: postgresql://user:password@host:port/dbname
database_url = config('DATABASE_URL', default=None)

if database_url:
    # إذا كان DATABASE_URL موجوداً، استخدمه (Docker/Production)
    # If DATABASE_URL exists, use it (Docker/Production)
    DATABASES = {
        "default": dj_database_url.parse(database_url)
    }
    # Enable pooling for dj_database_url if using postgres
    if DATABASES['default']['ENGINE'] == 'django.db.backends.postgresql':
        DATABASES['default']['ENGINE'] = 'dj_db_conn_pool.backends.postgresql'
        DATABASES['default']['POOL_OPTIONS'] = {
            'POOL_SIZE': config('DB_POOL_SIZE', default=20, cast=int),  # Increased for high traffic
            'MAX_OVERFLOW': config('DB_MAX_OVERFLOW', default=40, cast=int),  # Increased for peak loads
            'RECYCLE': 3600,  # 1 hour - recycle connections
            'PRE_PING': True,  # Verify connections before using
        }
        # Performance optimizations
        DATABASES['default']['OPTIONS'] = {
            'connect_timeout': 10,
            'options': '-c statement_timeout=30000 -c idle_in_transaction_session_timeout=30000',
        }
        # Connection age for pooling
        DATABASES['default']['CONN_MAX_AGE'] = 600  # 10 minutes
else:
    # Individual Database Settings (Priority 2: For Local Development)
    # إعدادات قاعدة البيانات الفردية (الأولوية الثانية: للتطوير المحلي)
    # في الإنتاج: يجب استخدام DATABASE_URL بدلاً من هذه القيم
    DATABASES = {
        "default": {
            "ENGINE": "dj_db_conn_pool.backends.postgresql", # Updated for pooling
            "NAME": config('DB_NAME'),  # مطلوب - اسم قاعدة البيانات
            "USER": config('DB_USER'),  # مطلوب - مستخدم قاعدة البيانات
            "PASSWORD": config('DB_PASSWORD'),  # مطلوب - كلمة مرور قوية
            "HOST": config('DB_HOST', default='localhost'),  # افتراضي: localhost
            "PORT": config('DB_PORT', default='5432'),  # افتراضي: 5432
            "POOL_OPTIONS": {
                'POOL_SIZE': 20,  # Increased for better performance
                'MAX_OVERFLOW': 40,  # Increased for peak loads
                'RECYCLE': 3600,  # 1 hour
                'PRE_PING': True,  # Verify connections before using
            },
            # Performance optimizations
            "OPTIONS": {
                'connect_timeout': 10,
                'options': '-c statement_timeout=30000 -c idle_in_transaction_session_timeout=30000',
            },
            # Connection age for pooling
            "CONN_MAX_AGE": 600,  # 10 minutes
        }
    }

# ============================================================================
# Production Security Validation
# التحقق من الأمان في الإنتاج
# ============================================================================
if not DEBUG:
    # في الإنتاج، تأكد من أن SECRET_KEY قوي
    # In production, ensure SECRET_KEY is strong
    if SECRET_KEY.startswith('django-insecure-'):
        raise ValueError(
            "SECURITY ERROR: You must set a strong SECRET_KEY in production! "
            "Do not use the default insecure key."
        )
    
    # في الإنتاج، تأكد من أن ALLOWED_HOSTS محددة
    # In production, ensure ALLOWED_HOSTS is specified
    if 'localhost' in ALLOWED_HOSTS or '127.0.0.1' in ALLOWED_HOSTS:
        import warnings
        warnings.warn(
            "SECURITY WARNING: localhost/127.0.0.1 in ALLOWED_HOSTS in production! "
            "This is insecure. Use your actual domain names.",
            UserWarning
        )


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "Asia/Damascus"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = "static/"
STATIC_ROOT = BASE_DIR / "staticfiles"

MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

# Default primary key field type
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# ============================================================================
# REST Framework Configuration
# إعدادات Django REST Framework للـ API
# ============================================================================
REST_FRAMEWORK = {
    # Schema Class for API Documentation
    # كلاس Schema لتوثيق الـ API تلقائياً (drf-spectacular)
    # يولد OpenAPI schema تلقائياً من serializers و views
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
    
    # Filter Backends
    # محركات الفلترة للبحث والتصفية في الـ API
    # django_filters: يسمح بالفلترة حسب الحقول (vendor, color, size, etc.)
    "DEFAULT_FILTER_BACKENDS": ["django_filters.rest_framework.DjangoFilterBackend"],
    
    # Pagination Configuration
    # إعدادات التقسيم للصفحات
    # StandardResultsSetPagination: تقسيم موحد يعمل للويب والموبايل
    # StandardResultsSetPagination: unified pagination that works for both web and mobile
    "DEFAULT_PAGINATION_CLASS": "core.pagination.StandardResultsSetPagination",
    
    # Page Size: عدد العناصر في كل صفحة
    # 24 منتج لكل صفحة (مناسب لعرض grid من المنتجات)
    # 24 products per page (suitable for product grid display)
    "PAGE_SIZE": 24,
    
    # Authentication Classes
    # فئات المصادقة - JWT Authentication
    # SimpleJWT: يستخدم JSON Web Tokens للمصادقة بدون حالة (stateless)
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework_simplejwt.authentication.JWTAuthentication",
        "rest_framework.authentication.SessionAuthentication",  # للـ Django Admin
    ],
    
    # Permission Classes
    # فئات الصلاحيات - افتراضياً: يجب أن يكون المستخدم مسجلاً
    # IsAuthenticated: يسمح فقط للمستخدمين المسجلين
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticated",
    ],
    
    # Throttling (Rate Limiting)
    # تحديد معدل الطلبات - حماية من الإفراط في الاستخدام
    "DEFAULT_THROTTLE_CLASSES": [
        "rest_framework.throttling.AnonRateThrottle",  # للمستخدمين غير المسجلين
        "rest_framework.throttling.UserRateThrottle",  # للمستخدمين المسجلين
    ],
    "DEFAULT_THROTTLE_RATES": {
        # In development: higher limits for easier testing
        # في التطوير: حدود أعلى لتسهيل الاختبار
        # In production: stricter limits for security
        # في الإنتاج: حدود أكثر صرامة للأمان
        "anon": "100/hour" if not DEBUG else "1000/hour",      # 100 طلب في الساعة (1000 في التطوير)
        "user": "1000/hour" if not DEBUG else "10000/hour",    # 1000 طلب في الساعة (10000 في التطوير)
        "admin": "5000/hour" if not DEBUG else "50000/hour",   # 5000 طلب في الساعة للـ admin (50000 في التطوير)
        "login": "5/minute",     # 5 محاولات تسجيل دخول في الدقيقة
        "register": "3/minute",  # 3 محاولات تسجيل في الدقيقة
    },
}

# ============================================================================
# CORS (Cross-Origin Resource Sharing) Settings
# إعدادات CORS للسماح للـ Frontend بالوصول للـ API
# ============================================================================
# CORS_ALLOWED_ORIGINS: قائمة المصادر المسموح لها بالوصول للـ API
# في التطوير: نسمح فقط لـ localhost:3000 (Next.js frontend)
# في الإنتاج: يجب تحديث هذه القائمة لتشمل domain الإنتاج
# Read from environment variable (set in docker-compose.yml) or use defaults
# قراءة من متغير البيئة (محدد في docker-compose.yml) أو استخدام القيم الافتراضية
CORS_ALLOWED_ORIGINS_ENV = config('CORS_ALLOWED_ORIGINS', default='')
if CORS_ALLOWED_ORIGINS_ENV:
    # Parse comma-separated origins from environment variable
    # تحليل المصادر المفصولة بفواصل من متغير البيئة
    CORS_ALLOWED_ORIGINS = [origin.strip() for origin in CORS_ALLOWED_ORIGINS_ENV.split(',')]
else:
    # Default origins for development
    # المصادر الافتراضية للتطوير
    CORS_ALLOWED_ORIGINS = [
        "http://localhost:3000",      # Next.js development server
        "http://127.0.0.1:3000",      # Alternative localhost
        "http://localhost:3001",      # Next.js fallback port
        "http://127.0.0.1:3001",      # Alternative fallback
    ]


# CORS_ALLOW_CREDENTIALS: السماح بإرسال credentials (cookies, auth headers)
# مهم للـ JWT authentication لاحقاً
CORS_ALLOW_CREDENTIALS = True

# ============================================================================
# drf-spectacular Settings (API Documentation)
# إعدادات drf-spectacular لتوثيق الـ API
# ============================================================================
SPECTACULAR_SETTINGS = {
    # API Title and Version
    # عنوان ونسخة الـ API
    "TITLE": "Trendyol-SY API",
    "DESCRIPTION": "Multi-vendor e-commerce platform API for Syrian market",
    "VERSION": "1.0.0",
    
    # API Server URLs
    # عناوين خوادم الـ API
    "SERVERS": [
        {"url": "http://localhost:8000", "description": "Development server"},
        # {"url": "https://api.trendyol-sy.com", "description": "Production server"},
    ],
    
    # Schema Settings
    # إعدادات Schema
    "SCHEMA_PATH_PREFIX": "/api/",  # Prefix لجميع مسارات الـ API
}

# ============================================================================
# JWT (JSON Web Token) Configuration
# إعدادات JWT للمصادقة
# ============================================================================
from datetime import timedelta

SIMPLE_JWT = {
    # Access Token Lifetime
    # مدة صلاحية Access Token (15 دقيقة)
    # Access Token يستخدم للوصول للـ API
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=15),
    
    # Refresh Token Lifetime
    # مدة صلاحية Refresh Token (7 أيام)
    # Refresh Token يستخدم لتجديد Access Token
    "REFRESH_TOKEN_LIFETIME": timedelta(days=7),
    
    # Rotate Refresh Tokens
    # تدوير Refresh Tokens: عند استخدام refresh token، يتم إنشاء refresh token جديد
    # هذا يحسن الأمان: إذا تم سرقة refresh token، يصبح غير صالح بعد الاستخدام
    "ROTATE_REFRESH_TOKENS": True,
    
    # Blacklist After Rotation
    # إضافة Refresh Token القديم للقائمة السوداء بعد التدوير
    # يمنع استخدام نفس refresh token مرتين
    "BLACKLIST_AFTER_ROTATION": True,
    
    # Update Last Login
    # تحديث last_login عند استخدام token
    "UPDATE_LAST_LOGIN": True,
    
    # Algorithm
    # خوارزمية التوقيع: HS256 (متناظرة - أسرع)
    "ALGORITHM": "HS256",
    
    # Signing Key
    # مفتاح التوقيع: يستخدم SECRET_KEY من Django
    "SIGNING_KEY": SECRET_KEY,
    
    # Token Type
    # نوع Token في الـ header
    "AUTH_HEADER_TYPES": ("Bearer",),
    
    # Auth Header Name
    # اسم الـ header للمصادقة
    "AUTH_HEADER_NAME": "HTTP_AUTHORIZATION",
    
    # User ID Field
    # الحقل المستخدم كـ user identifier في token
    "USER_ID_FIELD": "id",
    "USER_ID_CLAIM": "user_id",
    
    # Token Blacklist
    # استخدام blacklist للـ tokens الملغاة
    # يتطلب تثبيت: pip install django-rest-framework-simplejwt[blacklist]
    # "BLACKLIST_TOKEN_CHECKS": ["rest_framework_simplejwt.token_blacklist.models.BlacklistedToken"],
}

# ============================================================================
# Email Configuration (Gmail SMTP - Free)
# إعدادات البريد الإلكتروني (Gmail SMTP - مجاني)
# ============================================================================
# Email Backend
# محرك البريد الإلكتروني: SMTP
EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"

# SMTP Server Settings
# إعدادات خادم SMTP (Gmail)
EMAIL_HOST = config("EMAIL_HOST", default="smtp.gmail.com")
EMAIL_PORT = config("EMAIL_PORT", default=587, cast=int)
EMAIL_USE_TLS = config("EMAIL_USE_TLS", default=True, cast=bool)

# Email Credentials
# بيانات اعتماد البريد الإلكتروني
# يجب إنشاء App Password من Gmail (ليس كلمة المرور العادية)
# https://myaccount.google.com/apppasswords
EMAIL_HOST_USER = config("EMAIL_HOST_USER", default="")
EMAIL_HOST_PASSWORD = config("EMAIL_HOST_PASSWORD", default="")

# Default From Email
# البريد الإلكتروني الافتراضي للمرسل
DEFAULT_FROM_EMAIL = config("DEFAULT_FROM_EMAIL", default=EMAIL_HOST_USER)
SERVER_EMAIL = DEFAULT_FROM_EMAIL

# Email Subject Prefix
# بادئة موضوع البريد الإلكتروني
EMAIL_SUBJECT_PREFIX = "[Trendyol-SY] "

# ============================================================================
# Site Configuration (for Email Links)
# إعدادات الموقع (لروابط البريد الإلكتروني)
# ============================================================================
# Frontend URL (for email verification links)
# رابط Frontend (لروابط التحقق من البريد الإلكتروني)
FRONTEND_URL = config("FRONTEND_URL", default="http://localhost:3000")

# ============================================================================
# Production Security Headers
# إعدادات الأمان للإنتاج
# ============================================================================
# These settings only apply in production (DEBUG=False)
# هذه الإعدادات تعمل فقط في الإنتاج (DEBUG=False)

if not DEBUG:
    # HTTPS Security
    # أمان HTTPS
    SECURE_SSL_REDIRECT = config('SECURE_SSL_REDIRECT', default=True, cast=bool)
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    
    # Cookies Security
    # أمان Cookies
    SESSION_COOKIE_SECURE = True  # Only send cookies over HTTPS
    CSRF_COOKIE_SECURE = True     # Only send CSRF cookie over HTTPS
    SESSION_COOKIE_HTTPONLY = True  # Prevent JavaScript access to session cookie
    CSRF_COOKIE_HTTPONLY = True     # Prevent JavaScript access to CSRF cookie
    
    # Cookie Same-Site Policy
    # سياسة Same-Site للـ Cookies
    SESSION_COOKIE_SAMESITE = 'Lax'  # Protect against CSRF
    CSRF_COOKIE_SAMESITE = 'Lax'
    
    # Browser Security Headers
    # Headers أمان المتصفح
    SECURE_BROWSER_XSS_FILTER = True  # Enable XSS filter in browsers
    SECURE_CONTENT_TYPE_NOSNIFF = True  # Prevent MIME type sniffing
    X_FRAME_OPTIONS = 'DENY'  # Prevent clickjacking attacks
    
    # HSTS (HTTP Strict Transport Security)
    # أمان النقل الصارم - يجبر المتصفحات على استخدام HTTPS فقط
    SECURE_HSTS_SECONDS = 31536000  # 1 year
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True  # Apply to all subdomains
    SECURE_HSTS_PRELOAD = True  # Allow preloading in browsers

# ============================================================================
# Enhanced Password Validation
# تعزيز التحقق من كلمات المرور
# ============================================================================
# Override default password validators with stricter requirements
# تجاوز validators الافتراضية بمتطلبات أكثر صرامة
AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
        "OPTIONS": {
            "max_similarity": 0.6,  # More strict similarity check
        }
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
        "OPTIONS": {
            "min_length": 10,  # Increased from 8 to 10
        }
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

# ============================================================================
# Session Security Configuration
# إعدادات أمان الجلسات
# ============================================================================
SESSION_ENGINE = 'django.contrib.sessions.backends.db'  # Database-backed sessions
SESSION_COOKIE_AGE = 60 * 60 * 24 * 7  # 7 days (in seconds)
SESSION_EXPIRE_AT_BROWSER_CLOSE = False  # Session persists after browser closes
SESSION_SAVE_EVERY_REQUEST = True  # Refresh session on every request

# ============================================================================
# Logging Configuration
# إعدادات التسجيل (Logging)
# ============================================================================
# Comprehensive logging for debugging and monitoring
# تسجيل شامل للتصحيح والمراقبة
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    
    # Formatters - تنسيق الرسائل
    'formatters': {
        'verbose': {
            'format': '[{asctime}] {levelname} {name} {module} {message}',
            'style': '{',
            'datefmt': '%Y-%m-%d %H:%M:%S',
        },
        'simple': {
            'format': '[{levelname}] {message}',
            'style': '{',
        },
        'json': {
            'format': '{{"time": "{asctime}", "level": "{levelname}", "module": "{module}", "message": "{message}"}}',
            'style': '{',
            'datefmt': '%Y-%m-%d %H:%M:%S',
        },
    },
    
    # Handlers - معالجات الرسائل
    'handlers': {
        'console': {
            'level': 'DEBUG' if DEBUG else 'INFO',
            'class': 'logging.StreamHandler',
            'formatter': 'simple' if DEBUG else 'verbose',
        },
        'file': {
            'level': 'WARNING',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': BASE_DIR / 'logs' / 'django.log',
            'maxBytes': 10 * 1024 * 1024,  # 10 MB
            'backupCount': 5,
            'formatter': 'verbose',
        },
        'security_file': {
            'level': 'WARNING',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': BASE_DIR / 'logs' / 'security.log',
            'maxBytes': 10 * 1024 * 1024,  # 10 MB
            'backupCount': 10,
            'formatter': 'verbose',
        },
    },
    
    # Loggers - المسجلات
    'loggers': {
        'django': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
            'propagate': False,
        },
        'django.security': {
            'handlers': ['console', 'security_file'],
            'level': 'WARNING',
            'propagate': False,
        },
        'django.request': {
            'handlers': ['console', 'file'],
            'level': 'WARNING',
            'propagate': False,
        },
        'django.db.backends': {
            'handlers': ['console'],
            'level': 'WARNING',  # Set to DEBUG to see SQL queries
            'propagate': False,
        },
        # App-specific loggers
        'core': {
            'handlers': ['console', 'file'],
            'level': 'DEBUG' if DEBUG else 'INFO',
            'propagate': False,
        },
        'users': {
            'handlers': ['console', 'file'],
            'level': 'DEBUG' if DEBUG else 'INFO',
            'propagate': False,
        },
        'products': {
            'handlers': ['console', 'file'],
            'level': 'DEBUG' if DEBUG else 'INFO',
            'propagate': False,
        },
        'orders': {
            'handlers': ['console', 'file'],
            'level': 'DEBUG' if DEBUG else 'INFO',
            'propagate': False,
        },
    },
    
    # Root logger
    'root': {
        'handlers': ['console'],
        'level': 'WARNING',
    },
}

# Create logs directory if it doesn't exist
# إنشاء مجلد logs إذا لم يكن موجوداً
import os
LOGS_DIR = BASE_DIR / 'logs'
if not os.path.exists(LOGS_DIR):
    os.makedirs(LOGS_DIR)

# ============================================================================
# Caching Configuration (Redis)
# إعدادات التخزين المؤقت (Redis)
# ============================================================================
# Redis is optional - falls back to local memory cache if not available
# Redis اختياري - يرجع إلى ذاكرة التخزين المؤقت المحلية إذا لم يكن متاحاً

REDIS_URL = config('REDIS_URL', default='')

if REDIS_URL:
    # Use Redis for caching (Production)
    # استخدام Redis للتخزين المؤقت (الإنتاج)
    CACHES = {
        'default': {
            'BACKEND': 'django_redis.cache.RedisCache', # Updated to use django-redis
            'LOCATION': REDIS_URL,
            'OPTIONS': {
                'CLIENT_CLASS': 'django_redis.client.DefaultClient',
            },
            'KEY_PREFIX': 'trendyol',
            'TIMEOUT': 300,  # 5 minutes default
        }
    }

    
    # Use Redis for sessions too (faster)
    # استخدام Redis للجلسات أيضاً (أسرع)
    SESSION_ENGINE = 'django.contrib.sessions.backends.cache'
    SESSION_CACHE_ALIAS = 'default'
else:
    # Use local memory cache (Development)
    # استخدام ذاكرة التخزين المؤقت المحلية (التطوير)
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
            'LOCATION': 'unique-snowflake',
            'TIMEOUT': 300,
            'OPTIONS': {
                'MAX_ENTRIES': 1000,
            }
        }
    }

# ============================================================================
# Cache Timeouts (in seconds)
# أوقات انتهاء التخزين المؤقت (بالثواني)
# ============================================================================
# Cache Timeouts (in seconds) - Optimized for high-traffic systems
# مهلات انتهاء الـ Cache (بالثواني) - محسّنة للأنظمة عالية الحركة
CACHE_TIMEOUTS = {
    'products_list': 60 * 10,      # 10 minutes - قائمة المنتجات (reduced for freshness)
    'product_detail': 60 * 20,     # 20 minutes - تفاصيل المنتج (reduced for freshness)
    'categories': 60 * 60,          # 1 hour - الفئات (rarely change)
    'vendors': 60 * 30,             # 30 minutes - البائعين
    'settings': 60 * 60,            # 1 hour - الإعدادات (rarely change)
    'homepage': 60 * 5,             # 5 minutes - الصفحة الرئيسية (frequent updates)
    'product_variants': 60 * 15,   # 15 minutes - متغيرات المنتج
    'product_images': 60 * 30,     # 30 minutes - صور المنتج
}

# ============================================================================
# Data Upload Limits
# حدود رفع البيانات
# ============================================================================
# Maximum size for uploaded files
# الحجم الأقصى للملفات المرفوعة
DATA_UPLOAD_MAX_MEMORY_SIZE = 10 * 1024 * 1024  # 10 MB
FILE_UPLOAD_MAX_MEMORY_SIZE = 10 * 1024 * 1024  # 10 MB
DATA_UPLOAD_MAX_NUMBER_FIELDS = 1000  # Maximum form fields
