# Generated by Django 5.0 on 2025-12-27 14:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="NotificationPreference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("enable_order_notifications", models.BooleanField(default=True)),
                ("enable_user_notifications", models.BooleanField(default=True)),
                ("enable_vendor_notifications", models.BooleanField(default=True)),
                ("enable_system_notifications", models.BooleanField(default=True)),
                ("enable_product_notifications", models.BooleanField(default=True)),
                ("enable_category_notifications", models.BooleanField(default=True)),
                ("email_notifications_enabled", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        help_text="User these preferences belong to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_preferences",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Notification Preference",
                "verbose_name_plural": "Notification Preferences",
            },
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("order", "Order"),
                            ("user", "User"),
                            ("vendor", "Vendor"),
                            ("system", "System"),
                            ("product", "Product"),
                            ("category", "Category"),
                        ],
                        default="system",
                        help_text="Type of notification",
                        max_length=20,
                    ),
                ),
                (
                    "message",
                    models.CharField(
                        help_text="Notification message in English", max_length=500
                    ),
                ),
                (
                    "message_ar",
                    models.CharField(
                        blank=True,
                        help_text="Notification message in Arabic",
                        max_length=500,
                    ),
                ),
                (
                    "target_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("order", "Order"),
                            ("user", "User"),
                            ("vendor", "Vendor"),
                            ("product", "Product"),
                            ("category", "Category"),
                            ("system", "System"),
                        ],
                        help_text="Type of object this notification is about",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "target_id",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="ID of the object this notification is about",
                        null=True,
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        blank=True,
                        help_text='Action that triggered this notification (e.g., "order_created", "user_registered")',
                        max_length=100,
                    ),
                ),
                (
                    "is_read",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this notification has been read",
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional metadata about the notification",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="When this notification was created",
                    ),
                ),
                (
                    "read_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When this notification was marked as read",
                        null=True,
                    ),
                ),
                (
                    "recipient",
                    models.ForeignKey(
                        blank=True,
                        help_text="Admin user who should receive this notification. If null, notification is for all admins.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Notification",
                "verbose_name_plural": "Notifications",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["recipient", "is_read", "created_at"],
                        name="notificatio_recipie_86ea8b_idx",
                    ),
                    models.Index(
                        fields=["type", "is_read"], name="notificatio_type_5ae648_idx"
                    ),
                ],
            },
        ),
    ]
