# Generated by Django 5.0 on 2025-12-29 20:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("notifications", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="notification",
            name="target_id",
        ),
        migrations.RemoveField(
            model_name="notification",
            name="target_type",
        ),
        migrations.AddField(
            model_name="notification",
            name="target_content_type",
            field=models.ForeignKey(
                blank=True,
                help_text="Type of object this notification is about",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="contenttypes.contenttype",
            ),
        ),
        migrations.AddField(
            model_name="notification",
            name="target_object_id",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="ID of the object this notification is about",
                null=True,
            ),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["target_content_type", "target_object_id"],
                name="notificatio_target__dfbaf5_idx",
            ),
        ),
    ]
