# Generated by Django 5.0 on 2025-12-30 17:49

import uuid
import django.db.models.deletion
import orders.models
from django.conf import settings
from django.db import migrations, models
from django.db.models import Q


def generate_order_numbers_for_null(apps, schema_editor):
    """
    Generate order numbers for existing orders with NULL or empty order_number
    توليد أرقام الطلبات للطلبات الموجودة التي لديها order_number = NULL أو فارغ
    """
    Order = apps.get_model('orders', 'Order')
    
    # Find orders without order_number (NULL or empty string)
    # البحث عن الطلبات بدون order_number (NULL أو string فارغ)
    orders_without_number = Order.objects.filter(
        Q(order_number__isnull=True) | Q(order_number='')
    )
    
    for order in orders_without_number:
        # Generate unique order number
        # توليد رقم طلب فريد
        for attempt in range(10):
            order_number = f"ORD-{uuid.uuid4().hex[:8].upper()}"
            if not Order.objects.filter(order_number=order_number).exists():
                order.order_number = order_number
                order.save(update_fields=['order_number'])
                break
        else:
            # If all attempts failed, raise error
            # إذا فشلت جميع المحاولات، ارفع خطأ
            raise ValueError(f"Failed to generate unique order number for order {order.id} after 10 attempts")


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_order_number_and_more'),
        ('products', '0004_remove_productvariant_products_pr_sku_dcab68_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # First, generate order numbers for any existing NULL values
        # أولاً، توليد أرقام الطلبات لأي قيم NULL موجودة
        migrations.RunPython(
            generate_order_numbers_for_null,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='When the order was created / تاريخ إنشاء الطلب', verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer_address',
            field=models.TextField(help_text='Delivery address / عنوان التوصيل', verbose_name='Customer Address'),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer_name',
            field=models.CharField(help_text='Customer full name / اسم العميل الكامل', max_length=200, verbose_name='Customer Name'),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer_phone',
            field=models.CharField(help_text='Customer phone number / رقم هاتف العميل', max_length=20, verbose_name='Customer Phone'),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_fee',
            field=models.DecimalField(decimal_places=2, default=orders.models.zero_decimal, help_text='Yalla Go delivery fee / رسوم التوصيل (Yalla Go)', max_digits=10, verbose_name='Delivery Fee'),
        ),
        migrations.AlterField(
            model_name='order',
            name='is_guest_order',
            field=models.BooleanField(default=False, help_text='True if this order was placed without user authentication / صحيح إذا تم تقديم الطلب بدون تسجيل دخول', verbose_name='Is Guest Order'),
        ),
        migrations.AlterField(
            model_name='order',
            name='notes',
            field=models.TextField(blank=True, help_text='Additional notes about the order / ملاحظات إضافية حول الطلب', verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.CharField(blank=True, help_text='Order number (auto-generated if not provided) / رقم الطلب (يُنشأ تلقائياً إذا لم يُحدد)', max_length=50, null=False, unique=True, verbose_name='Order Number'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_type',
            field=models.CharField(choices=[('online', 'Online (Delivery) / أونلاين (توصيل)'), ('pos', 'POS (In-store) / نقطة البيع (في المتجر)')], default='online', help_text='Type of order / نوع الطلب', max_length=20, verbose_name='Order Type'),
        ),
        migrations.AlterField(
            model_name='order',
            name='platform_commission',
            field=models.DecimalField(decimal_places=2, default=orders.models.zero_decimal, help_text='Platform commission (10% of subtotal) / عمولة المنصة (10% من المجموع الفرعي)', max_digits=10, verbose_name='Platform Commission'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending / قيد الانتظار'), ('confirmed', 'Confirmed / مؤكد'), ('shipped', 'Shipped / تم الشحن'), ('delivered', 'Delivered / تم التسليم'), ('cancelled', 'Cancelled / ملغي')], db_index=True, default='pending', help_text='Order status / حالة الطلب', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='order',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=orders.models.zero_decimal, help_text='Order subtotal (before delivery fee) / المجموع الفرعي (قبل رسوم التوصيل)', max_digits=10, verbose_name='Subtotal'),
        ),
        migrations.AlterField(
            model_name='order',
            name='total',
            field=models.DecimalField(decimal_places=2, default=orders.models.zero_decimal, help_text='Order total (subtotal + delivery fee) / الإجمالي (المجموع الفرعي + رسوم التوصيل)', max_digits=10, verbose_name='Total'),
        ),
        migrations.AlterField(
            model_name='order',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='When the order was last updated / تاريخ آخر تحديث للطلب', verbose_name='Updated At'),
        ),
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(blank=True, help_text='User who placed this order (null for guest orders) / المستخدم الذي قدم الطلب (null للطلبات بدون تسجيل)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='When this item was added to the order / تاريخ إضافة هذا العنصر للطلب', verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(help_text='Order this item belongs to / الطلب الذي ينتمي إليه هذا العنصر', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order', verbose_name='Order'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='Price per unit at time of order (in Syrian Pounds) / السعر لكل وحدة وقت الطلب (بالليرة السورية)', max_digits=10, verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product_variant',
            field=models.ForeignKey(help_text='Product variant ordered / متغير المنتج المطلوب', on_delete=django.db.models.deletion.PROTECT, to='products.productvariant', verbose_name='Product Variant'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='quantity',
            field=models.PositiveIntegerField(default=1, help_text='Number of items ordered / عدد العناصر المطلوبة', verbose_name='Quantity'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['order_type', 'status'], name='orders_orde_order_t_1378c7_idx'),
        ),
        migrations.AddIndex(
            model_name='orderitem',
            index=models.Index(fields=['order', 'product_variant'], name='orders_orde_order_i_02f6fe_idx'),
        ),
    ]
