# Generated by Django 5.0 on 2025-12-19 23:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("vendors", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("slug", models.SlugField(blank=True, max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "base_price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Price in Syrian Pounds",
                        max_digits=10,
                    ),
                ),
                (
                    "product_type",
                    models.CharField(
                        choices=[("shoes", "Shoes"), ("bags", "Bags")], max_length=20
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "vendor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="products",
                        to="vendors.vendor",
                    ),
                ),
            ],
            options={
                "verbose_name": "Product",
                "verbose_name_plural": "Products",
                "ordering": ["-created_at"],
                "unique_together": {("vendor", "slug")},
            },
        ),
        migrations.CreateModel(
            name="ProductVariant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("color", models.CharField(max_length=50)),
                (
                    "color_hex",
                    models.CharField(
                        blank=True, help_text="Hex color code", max_length=7
                    ),
                ),
                (
                    "size",
                    models.CharField(
                        blank=True,
                        help_text="For shoes (e.g., 25, 30, 38)",
                        max_length=20,
                    ),
                ),
                (
                    "model",
                    models.CharField(
                        blank=True, help_text="Model/Style name", max_length=100
                    ),
                ),
                ("sku", models.CharField(blank=True, max_length=100, unique=True)),
                ("stock_quantity", models.PositiveIntegerField(default=0)),
                (
                    "price_override",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="products/"),
                ),
                ("is_available", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="variants",
                        to="products.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Product Variant",
                "verbose_name_plural": "Product Variants",
                "ordering": ["color", "size"],
            },
        ),
    ]
