# Generated by Django 5.1 on 2025-12-24 19:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
        ("vendors", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="product_type",
            field=models.CharField(
                blank=True,
                choices=[("shoes", "Shoes"), ("bags", "Bags")],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="vendor",
            field=models.ForeignKey(
                help_text="البائع/الماركة",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="products",
                to="vendors.vendor",
                verbose_name="Vendor",
            ),
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="اسم الفئة بالإنجليزية",
                        max_length=100,
                        verbose_name="Category Name (English)",
                    ),
                ),
                (
                    "name_ar",
                    models.CharField(
                        help_text="اسم الفئة بالعربية",
                        max_length=100,
                        verbose_name="Category Name (Arabic)",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True,
                        help_text="الرابط المختصر (يُنشأ تلقائياً)",
                        max_length=100,
                        unique=True,
                        verbose_name="Slug",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="وصف الفئة بالإنجليزية",
                        verbose_name="Description (English)",
                    ),
                ),
                (
                    "description_ar",
                    models.TextField(
                        blank=True,
                        help_text="وصف الفئة بالعربية",
                        verbose_name="Description (Arabic)",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        help_text="صورة الفئة (مربعة، 400x400 بكسل)",
                        null=True,
                        upload_to="categories/",
                        verbose_name="Category Image",
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        blank=True,
                        help_text="CSS class أو اسم الأيقونة",
                        max_length=100,
                        verbose_name="Icon",
                    ),
                ),
                (
                    "display_order",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="ترتيب العرض (0 = الأول)",
                        verbose_name="Display Order",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="هل الفئة نشطة؟",
                        verbose_name="Is Active",
                    ),
                ),
                (
                    "is_featured",
                    models.BooleanField(
                        default=False,
                        help_text="هل الفئة مميزة؟ (تظهر في الصفحة الرئيسية)",
                        verbose_name="Is Featured",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        help_text="الفئة الأم (اتركها فارغة للفئات الرئيسية)",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="products.category",
                        verbose_name="Parent Category",
                    ),
                ),
            ],
            options={
                "verbose_name": "Category",
                "verbose_name_plural": "Categories",
                "ordering": ["display_order", "name"],
            },
        ),
        migrations.AddField(
            model_name="product",
            name="category",
            field=models.ForeignKey(
                blank=True,
                help_text="فئة المنتج",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="products",
                to="products.category",
                verbose_name="Category",
            ),
        ),
    ]
