# Generated by Django 5.0 on 2025-12-30 16:28

import django.db.models.deletion
import products.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_productvariant_sku_and_more'),
        ('vendors', '0004_alter_vendor_primary_color_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='productvariant',
            name='products_pr_sku_dcab68_idx',
        ),
        migrations.AlterUniqueTogether(
            name='product',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='الفئة الأم (اتركها فارغة للفئات الرئيسية)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='products.category', verbose_name='Parent Category'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='color_hex',
            field=models.CharField(blank=True, help_text='Hex color code', max_length=7, validators=[products.models.validate_color_hex]),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(fields=('vendor', 'slug'), name='uq_product_vendor_slug'),
        ),
    ]
