# Generated by Django 5.0 on 2025-12-31 13:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_remove_productvariant_products_pr_sku_dcab68_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='صورة المنتج', upload_to='products/images/', verbose_name='Image')),
                ('display_order', models.PositiveIntegerField(default=0, help_text='ترتيب العرض (0 = الأول، الأصغر يظهر أولاً)', verbose_name='Display Order')),
                ('is_primary', models.BooleanField(default=False, help_text='هل هذه الصورة الأساسية للمنتج؟ (يجب أن تكون صورة واحدة فقط أساسية)', verbose_name='Is Primary')),
                ('alt_text', models.CharField(blank=True, help_text='النص البديل للصورة (لتحسين SEO وإمكانية الوصول)', max_length=200, verbose_name='Alt Text')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(help_text='المنتج المرتبط', on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.product', verbose_name='Product')),
            ],
            options={
                'verbose_name': 'Product Image',
                'verbose_name_plural': 'Product Images',
                'ordering': ['display_order', 'created_at'],
                'indexes': [models.Index(fields=['product', 'display_order'], name='products_pr_product_48d699_idx'), models.Index(fields=['product', 'is_primary'], name='products_pr_product_1b7905_idx')],
            },
        ),
    ]
