# Generated by Django 5.0 on 2025-12-30 18:17

import cart.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0004_remove_productvariant_products_pr_sku_dcab68_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, db_index=True, help_text='Session key for guest carts (null for authenticated users) / مفتاح الجلسة للسلل الضيفية (null للمستخدمين المسجلين)', max_length=40, null=True, verbose_name='Session Key')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this cart was created / متى تم إنشاء هذه السلة', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this cart was last updated / متى تم تحديث هذه السلة آخر مرة', verbose_name='Updated At')),
                ('user', models.OneToOneField(blank=True, help_text='User who owns this cart (null for guest carts) / المستخدم الذي يملك هذه السلة (null للسلل الضيفية)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cart', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Cart',
                'verbose_name_plural': 'Carts',
                'db_table': 'cart',
            },
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, help_text='Number of items / عدد العناصر', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Quantity')),
                ('price', models.DecimalField(decimal_places=2, default=cart.models.zero_decimal, help_text='Price per item (snapshot at time of adding) / السعر لكل عنصر (لقطة في وقت الإضافة)', max_digits=10, verbose_name='Price')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this item was added to cart / متى تم إضافة هذا العنصر للسلة', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this item was last updated / متى تم تحديث هذا العنصر آخر مرة', verbose_name='Updated At')),
                ('cart', models.ForeignKey(help_text='Cart this item belongs to / السلة التي ينتمي إليها هذا العنصر', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='cart.cart', verbose_name='Cart')),
                ('variant', models.ForeignKey(help_text='Product variant being purchased / متغير المنتج الذي يتم شراؤه', on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='products.productvariant', verbose_name='Product Variant')),
            ],
            options={
                'verbose_name': 'Cart Item',
                'verbose_name_plural': 'Cart Items',
                'db_table': 'cart_item',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='cart',
            index=models.Index(fields=['user'], name='cart_user_idx'),
        ),
        migrations.AddIndex(
            model_name='cart',
            index=models.Index(fields=['session_key'], name='cart_session_key_idx'),
        ),
        migrations.AddIndex(
            model_name='cart',
            index=models.Index(fields=['updated_at'], name='cart_updated_at_idx'),
        ),
        migrations.AddConstraint(
            model_name='cart',
            constraint=models.CheckConstraint(check=models.Q(('user__isnull', False), ('session_key__isnull', False), _connector='OR'), name='cart_must_have_user_or_session'),
        ),
        migrations.AddIndex(
            model_name='cartitem',
            index=models.Index(fields=['cart'], name='cart_item_cart_idx'),
        ),
        migrations.AddIndex(
            model_name='cartitem',
            index=models.Index(fields=['variant'], name='cart_item_variant_idx'),
        ),
        migrations.AddIndex(
            model_name='cartitem',
            index=models.Index(fields=['created_at'], name='cart_item_created_at_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together={('cart', 'variant')},
        ),
    ]
