# Generated by Django 5.1 on 2025-12-25 15:41

import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("products", "0002_alter_product_product_type_alter_product_vendor_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Banner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Banner title in English / عنوان البانر بالإنجليزية",
                        max_length=200,
                        verbose_name="Title / العنوان",
                    ),
                ),
                (
                    "title_ar",
                    models.CharField(
                        help_text="Banner title in Arabic / عنوان البانر بالعربية",
                        max_length=200,
                        verbose_name="Title (Arabic) / العنوان (عربي)",
                    ),
                ),
                (
                    "subtitle",
                    models.CharField(
                        blank=True,
                        help_text="Banner subtitle in English / العنوان الفرعي بالإنجليزية",
                        max_length=300,
                        verbose_name="Subtitle / العنوان الفرعي",
                    ),
                ),
                (
                    "subtitle_ar",
                    models.CharField(
                        blank=True,
                        help_text="Banner subtitle in Arabic / العنوان الفرعي بالعربية",
                        max_length=300,
                        verbose_name="Subtitle (Arabic) / العنوان الفرعي (عربي)",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        help_text="Banner image / صورة البانر",
                        upload_to="promotions/banners/",
                        verbose_name="Image / الصورة",
                    ),
                ),
                (
                    "link_type",
                    models.CharField(
                        choices=[
                            ("url", "URL / رابط مباشر"),
                            ("product", "Product / منتج"),
                            ("category", "Category / فئة"),
                        ],
                        default="url",
                        help_text="Type of link / نوع الرابط",
                        max_length=20,
                        verbose_name="Link Type / نوع الرابط",
                    ),
                ),
                (
                    "link",
                    models.CharField(
                        help_text="URL, product slug, or category slug / رابط URL أو معرف المنتج أو الفئة",
                        max_length=500,
                        verbose_name="Link / الرابط",
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        choices=[
                            ("hero", "Hero Banner / البانر الرئيسي"),
                            ("sidebar", "Sidebar / الشريط الجانبي"),
                            ("popup", "Popup / النافذة المنبثقة"),
                            ("category", "Category / الفئة"),
                        ],
                        default="hero",
                        help_text="Where the banner will be displayed / مكان عرض البانر",
                        max_length=20,
                        verbose_name="Location / الموقع",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Display order (lower numbers appear first) / ترتيب العرض (الأرقام الأقل تظهر أولاً)",
                        verbose_name="Order / الترتيب",
                    ),
                ),
                (
                    "start_date",
                    models.DateTimeField(
                        help_text="When the banner should start showing / متى يبدأ عرض البانر",
                        verbose_name="Start Date / تاريخ البدء",
                    ),
                ),
                (
                    "end_date",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the banner should stop showing (optional) / متى يتوقف عرض البانر (اختياري)",
                        null=True,
                        verbose_name="End Date / تاريخ الانتهاء",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether the banner is currently active / هل البانر نشط حالياً",
                        verbose_name="Active / نشط",
                    ),
                ),
                (
                    "views",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Number of times the banner was viewed / عدد مرات مشاهدة البانر",
                        verbose_name="Views / المشاهدات",
                    ),
                ),
                (
                    "clicks",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Number of times the banner was clicked / عدد مرات النقر على البانر",
                        verbose_name="Clicks / النقرات",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Banner / البانر",
                "verbose_name_plural": "Banners / البانرات",
                "ordering": ["order", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["location", "is_active"],
                        name="promotions__locatio_5683c8_idx",
                    ),
                    models.Index(
                        fields=["start_date", "end_date"],
                        name="promotions__start_d_df3d18_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Story",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Story title in English / عنوان القصة بالإنجليزية",
                        max_length=200,
                        verbose_name="Title / العنوان",
                    ),
                ),
                (
                    "title_ar",
                    models.CharField(
                        help_text="Story title in Arabic / عنوان القصة بالعربية",
                        max_length=200,
                        verbose_name="Title (Arabic) / العنوان (عربي)",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        help_text="Story image / صورة القصة",
                        upload_to="promotions/stories/",
                        verbose_name="Image / الصورة",
                    ),
                ),
                (
                    "link_type",
                    models.CharField(
                        choices=[
                            ("url", "URL / رابط مباشر"),
                            ("product", "Product / منتج"),
                            ("category", "Category / فئة"),
                        ],
                        default="url",
                        help_text="Type of link / نوع الرابط",
                        max_length=20,
                        verbose_name="Link Type / نوع الرابط",
                    ),
                ),
                (
                    "link",
                    models.CharField(
                        blank=True,
                        help_text="URL, product slug, or category slug (optional) / رابط URL أو معرف المنتج أو الفئة (اختياري)",
                        max_length=500,
                        verbose_name="Link / الرابط",
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        help_text="When the story should expire / متى تنتهي القصة",
                        verbose_name="Expires At / ينتهي في",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether the story is currently active / هل القصة نشطة حالياً",
                        verbose_name="Active / نشط",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Display order (lower numbers appear first) / ترتيب العرض (الأرقام الأقل تظهر أولاً)",
                        verbose_name="Order / الترتيب",
                    ),
                ),
                (
                    "views",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Number of times the story was viewed / عدد مرات مشاهدة القصة",
                        verbose_name="Views / المشاهدات",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Story / القصة",
                "verbose_name_plural": "Stories / القصص",
                "ordering": ["order", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["is_active", "expires_at"],
                        name="promotions__is_acti_85e59a_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Coupon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Coupon code (must be unique) / رمز الكوبون (يجب أن يكون فريداً)",
                        max_length=50,
                        unique=True,
                        verbose_name="Code / الرمز",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Coupon description in English / وصف الكوبون بالإنجليزية",
                        verbose_name="Description / الوصف",
                    ),
                ),
                (
                    "description_ar",
                    models.TextField(
                        blank=True,
                        help_text="Coupon description in Arabic / وصف الكوبون بالعربية",
                        verbose_name="Description (Arabic) / الوصف (عربي)",
                    ),
                ),
                (
                    "discount_type",
                    models.CharField(
                        choices=[
                            ("percentage", "Percentage / نسبة مئوية"),
                            ("fixed", "Fixed Amount / مبلغ ثابت"),
                        ],
                        default="percentage",
                        help_text="Type of discount / نوع الخصم",
                        max_length=20,
                        verbose_name="Discount Type / نوع الخصم",
                    ),
                ),
                (
                    "discount_value",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Discount amount (percentage or fixed) / قيمة الخصم (نسبة مئوية أو مبلغ ثابت)",
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Discount Value / قيمة الخصم",
                    ),
                ),
                (
                    "min_order",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Minimum order value to use this coupon / أقل قيمة طلب لاستخدام هذا الكوبون",
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Minimum Order / أقل قيمة طلب",
                    ),
                ),
                (
                    "max_discount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Maximum discount amount (for percentage discounts) / أقصى مبلغ خصم (للخصومات النسبية)",
                        max_digits=10,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Maximum Discount / أقصى خصم",
                    ),
                ),
                (
                    "usage_limit",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Maximum number of times this coupon can be used (null = unlimited) / الحد الأقصى لاستخدام الكوبون (null = غير محدود)",
                        null=True,
                        verbose_name="Usage Limit / حد الاستخدام",
                    ),
                ),
                (
                    "used_count",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Number of times this coupon has been used / عدد مرات استخدام الكوبون",
                        verbose_name="Used Count / عدد مرات الاستخدام",
                    ),
                ),
                (
                    "applicable_to",
                    models.CharField(
                        choices=[
                            ("all", "All Products / جميع المنتجات"),
                            ("category", "Category / فئة"),
                            ("product", "Product / منتج"),
                            ("user", "Specific Users / مستخدمون محددون"),
                        ],
                        default="all",
                        help_text="What this coupon applies to / ما يمكن تطبيق الكوبون عليه",
                        max_length=20,
                        verbose_name="Applicable To / قابل للتطبيق على",
                    ),
                ),
                (
                    "start_date",
                    models.DateTimeField(
                        help_text="When the coupon becomes valid / متى يصبح الكوبون صالحاً",
                        verbose_name="Start Date / تاريخ البدء",
                    ),
                ),
                (
                    "end_date",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the coupon expires (optional) / متى ينتهي الكوبون (اختياري)",
                        null=True,
                        verbose_name="End Date / تاريخ الانتهاء",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether the coupon is currently active / هل الكوبون نشط حالياً",
                        verbose_name="Active / نشط",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "applicable_categories",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Categories this coupon applies to (if applicable_to = category) / الفئات التي ينطبق عليها الكوبون (إذا applicable_to = category)",
                        related_name="coupons",
                        to="products.category",
                        verbose_name="Applicable Categories / الفئات القابلة للتطبيق",
                    ),
                ),
                (
                    "applicable_products",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Products this coupon applies to (if applicable_to = product) / المنتجات التي ينطبق عليها الكوبون (إذا applicable_to = product)",
                        related_name="coupons",
                        to="products.product",
                        verbose_name="Applicable Products / المنتجات القابلة للتطبيق",
                    ),
                ),
                (
                    "applicable_users",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Users who can use this coupon (if applicable_to = user) / المستخدمون الذين يمكنهم استخدام الكوبون (إذا applicable_to = user)",
                        related_name="coupons",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Applicable Users / المستخدمون القابلون للتطبيق",
                    ),
                ),
            ],
            options={
                "verbose_name": "Coupon / الكوبون",
                "verbose_name_plural": "Coupons / الكوبونات",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["code"], name="promotions__code_acae7b_idx"),
                    models.Index(
                        fields=["is_active", "start_date", "end_date"],
                        name="promotions__is_acti_a01a21_idx",
                    ),
                ],
            },
        ),
    ]
