# Generated by Django 5.1 on 2025-12-24 12:43

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Language",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="ISO language code (e.g., 'ar', 'en')",
                        max_length=10,
                        unique=True,
                        verbose_name="Language Code",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Language name in English",
                        max_length=50,
                        verbose_name="Language Name (English)",
                    ),
                ),
                (
                    "native_name",
                    models.CharField(
                        help_text="Language name in its native script (e.g., 'العربية')",
                        max_length=50,
                        verbose_name="Native Name",
                    ),
                ),
                (
                    "flag_emoji",
                    models.CharField(
                        blank=True,
                        help_text="Country flag emoji (e.g., '🇸🇾')",
                        max_length=10,
                        verbose_name="Flag Emoji",
                    ),
                ),
                (
                    "flag_url",
                    models.URLField(
                        blank=True,
                        help_text="URL to flag image (alternative to emoji)",
                        max_length=500,
                        verbose_name="Flag Image URL",
                    ),
                ),
                (
                    "is_rtl",
                    models.BooleanField(
                        default=False,
                        help_text="Is this a right-to-left language",
                        verbose_name="Is RTL",
                    ),
                ),
                (
                    "is_default",
                    models.BooleanField(
                        default=False,
                        help_text="Is this the default language",
                        verbose_name="Is Default",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Is this language available for selection",
                        verbose_name="Is Active",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Order in language selector (lower = first)",
                        verbose_name="Display Order",
                    ),
                ),
            ],
            options={
                "verbose_name": "Language",
                "verbose_name_plural": "Languages",
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="PaymentMethod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Unique code for this payment method (e.g., 'cod', 'visa')",
                        max_length=50,
                        unique=True,
                        verbose_name="Code",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Payment method name - English",
                        max_length=100,
                        verbose_name="Name (English)",
                    ),
                ),
                (
                    "name_ar",
                    models.CharField(
                        help_text="Payment method name - Arabic",
                        max_length=100,
                        verbose_name="Name (Arabic)",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Description shown to customers - English",
                        verbose_name="Description (English)",
                    ),
                ),
                (
                    "description_ar",
                    models.TextField(
                        blank=True,
                        help_text="Description shown to customers - Arabic",
                        verbose_name="Description (Arabic)",
                    ),
                ),
                (
                    "instructions",
                    models.TextField(
                        blank=True,
                        help_text="Payment instructions for customers - English",
                        verbose_name="Instructions (English)",
                    ),
                ),
                (
                    "instructions_ar",
                    models.TextField(
                        blank=True,
                        help_text="Payment instructions for customers - Arabic",
                        verbose_name="Instructions (Arabic)",
                    ),
                ),
                (
                    "icon_url",
                    models.URLField(
                        blank=True,
                        help_text="URL to payment method icon/logo",
                        max_length=500,
                        verbose_name="Icon URL",
                    ),
                ),
                (
                    "fee_type",
                    models.CharField(
                        choices=[
                            ("none", "No Fee"),
                            ("fixed", "Fixed Amount"),
                            ("percentage", "Percentage"),
                        ],
                        default="none",
                        help_text="Type of fee for this payment method",
                        max_length=20,
                        verbose_name="Fee Type",
                    ),
                ),
                (
                    "fee_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Fee amount (fixed) or percentage",
                        max_digits=10,
                        verbose_name="Fee Amount",
                    ),
                ),
                (
                    "min_order_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Minimum order amount for this payment method",
                        max_digits=10,
                        null=True,
                        verbose_name="Minimum Order Amount",
                    ),
                ),
                (
                    "max_order_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Maximum order amount for this payment method",
                        max_digits=10,
                        null=True,
                        verbose_name="Maximum Order Amount",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Order in checkout (lower = first)",
                        verbose_name="Display Order",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Is this payment method available",
                        verbose_name="Is Active",
                    ),
                ),
                (
                    "is_default",
                    models.BooleanField(
                        default=False,
                        help_text="Pre-select this payment method in checkout",
                        verbose_name="Is Default",
                    ),
                ),
            ],
            options={
                "verbose_name": "Payment Method",
                "verbose_name_plural": "Payment Methods",
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="ShippingMethod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Unique code for this shipping method",
                        max_length=50,
                        unique=True,
                        verbose_name="Code",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Shipping method name - English",
                        max_length=100,
                        verbose_name="Name (English)",
                    ),
                ),
                (
                    "name_ar",
                    models.CharField(
                        help_text="Shipping method name - Arabic",
                        max_length=100,
                        verbose_name="Name (Arabic)",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Description shown to customers - English",
                        verbose_name="Description (English)",
                    ),
                ),
                (
                    "description_ar",
                    models.TextField(
                        blank=True,
                        help_text="Description shown to customers - Arabic",
                        verbose_name="Description (Arabic)",
                    ),
                ),
                (
                    "estimated_days_min",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="Minimum estimated delivery days",
                        verbose_name="Minimum Days",
                    ),
                ),
                (
                    "estimated_days_max",
                    models.PositiveIntegerField(
                        default=3,
                        help_text="Maximum estimated delivery days",
                        verbose_name="Maximum Days",
                    ),
                ),
                (
                    "rate_type",
                    models.CharField(
                        choices=[
                            ("free", "Free Shipping"),
                            ("flat", "Flat Rate"),
                            ("weight", "By Weight"),
                            ("price", "By Order Price"),
                        ],
                        default="flat",
                        help_text="How shipping rate is calculated",
                        max_length=20,
                        verbose_name="Rate Type",
                    ),
                ),
                (
                    "rate_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Shipping rate (flat rate or per unit)",
                        max_digits=10,
                        verbose_name="Rate Amount",
                    ),
                ),
                (
                    "free_shipping_threshold",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Order amount for free shipping (leave empty if not applicable)",
                        max_digits=10,
                        null=True,
                        verbose_name="Free Shipping Threshold",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Order in checkout (lower = first)",
                        verbose_name="Display Order",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Is this shipping method available",
                        verbose_name="Is Active",
                    ),
                ),
                (
                    "is_default",
                    models.BooleanField(
                        default=False,
                        help_text="Pre-select this shipping method in checkout",
                        verbose_name="Is Default",
                    ),
                ),
            ],
            options={
                "verbose_name": "Shipping Method",
                "verbose_name_plural": "Shipping Methods",
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="SiteSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "site_name",
                    models.CharField(
                        default="Yalla Buy",
                        help_text="The site name displayed in header and title - English",
                        max_length=100,
                        validators=[
                            django.core.validators.MinLengthValidator(2),
                            django.core.validators.MaxLengthValidator(100),
                        ],
                        verbose_name="Site Name (English)",
                    ),
                ),
                (
                    "site_name_ar",
                    models.CharField(
                        default="يلا باي",
                        help_text="The site name displayed in header and title - Arabic",
                        max_length=100,
                        validators=[
                            django.core.validators.MinLengthValidator(2),
                            django.core.validators.MaxLengthValidator(100),
                        ],
                        verbose_name="Site Name (Arabic)",
                    ),
                ),
                (
                    "tagline",
                    models.CharField(
                        blank=True,
                        default="Order in Seconds",
                        help_text="Short slogan displayed under the logo - English",
                        max_length=200,
                        verbose_name="Tagline (English)",
                    ),
                ),
                (
                    "tagline_ar",
                    models.CharField(
                        blank=True,
                        default="اطلبها بثواني",
                        help_text="Short slogan displayed under the logo - Arabic",
                        max_length=200,
                        verbose_name="Tagline (Arabic)",
                    ),
                ),
                (
                    "logo_url",
                    models.URLField(
                        blank=True,
                        help_text="Full URL to the site logo image (recommended: 200x60px PNG)",
                        max_length=500,
                        verbose_name="Logo URL",
                    ),
                ),
                (
                    "logo_dark_url",
                    models.URLField(
                        blank=True,
                        help_text="Logo for dark mode/dark backgrounds",
                        max_length=500,
                        verbose_name="Logo URL (Dark Mode)",
                    ),
                ),
                (
                    "favicon_url",
                    models.URLField(
                        blank=True,
                        help_text="Full URL to the favicon image (recommended: 32x32px ICO/PNG)",
                        max_length=500,
                        verbose_name="Favicon URL",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        default="Your one-stop shop for shoes and bags in Syria",
                        help_text="Full description of the site - English",
                        verbose_name="Site Description (English)",
                    ),
                ),
                (
                    "description_ar",
                    models.TextField(
                        blank=True,
                        default="وجهتك الأولى للأحذية والحقائب في سوريا",
                        help_text="Full description of the site - Arabic",
                        verbose_name="Site Description (Arabic)",
                    ),
                ),
                (
                    "meta_title",
                    models.CharField(
                        blank=True,
                        default="Yalla Buy - Online Shopping in Syria",
                        help_text="SEO title for search engines (max 70 characters)",
                        max_length=70,
                        verbose_name="Meta Title",
                    ),
                ),
                (
                    "meta_title_ar",
                    models.CharField(
                        blank=True,
                        default="يلا باي - تسوق اونلاين في سوريا",
                        help_text="SEO title for search engines - Arabic",
                        max_length=70,
                        verbose_name="Meta Title (Arabic)",
                    ),
                ),
                (
                    "meta_description",
                    models.CharField(
                        blank=True,
                        default="Shop the latest shoes and bags from trusted vendors in Syria. Fast delivery, secure payment.",
                        help_text="SEO description for search engines (max 160 characters)",
                        max_length=160,
                        verbose_name="Meta Description",
                    ),
                ),
                (
                    "meta_description_ar",
                    models.CharField(
                        blank=True,
                        default="تسوق أحدث الأحذية والحقائب من بائعين موثوقين في سوريا. توصيل سريع ودفع آمن.",
                        help_text="SEO description for search engines - Arabic",
                        max_length=160,
                        verbose_name="Meta Description (Arabic)",
                    ),
                ),
                (
                    "meta_keywords",
                    models.TextField(
                        blank=True,
                        default="shoes, bags, online shopping, syria, yalla buy",
                        help_text="Comma-separated keywords for SEO",
                        verbose_name="Meta Keywords",
                    ),
                ),
                (
                    "meta_keywords_ar",
                    models.TextField(
                        blank=True,
                        default="أحذية, حقائب, تسوق اونلاين, سوريا, يلا باي",
                        help_text="Comma-separated keywords for SEO - Arabic",
                        verbose_name="Meta Keywords (Arabic)",
                    ),
                ),
                (
                    "contact_email",
                    models.EmailField(
                        default="info@yallabuy.sy",
                        help_text="Main contact email address",
                        max_length=254,
                        verbose_name="Contact Email",
                    ),
                ),
                (
                    "contact_phone",
                    models.CharField(
                        blank=True,
                        default="+963 11 123 4567",
                        help_text="Main contact phone number",
                        max_length=20,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Enter a valid phone number (7-20 digits, may include +, spaces, hyphens)",
                                regex="^\\+?[0-9\\s\\-\\(\\)]{7,20}$",
                            )
                        ],
                        verbose_name="Contact Phone",
                    ),
                ),
                (
                    "contact_whatsapp",
                    models.CharField(
                        blank=True,
                        help_text="WhatsApp number for customer support (with country code)",
                        max_length=20,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Enter a valid phone number (7-20 digits, may include +, spaces, hyphens)",
                                regex="^\\+?[0-9\\s\\-\\(\\)]{7,20}$",
                            )
                        ],
                        verbose_name="WhatsApp Number",
                    ),
                ),
                (
                    "address",
                    models.TextField(
                        blank=True,
                        default="Damascus, Syria",
                        help_text="Physical address of the company - English",
                        verbose_name="Address (English)",
                    ),
                ),
                (
                    "address_ar",
                    models.TextField(
                        blank=True,
                        default="دمشق، سوريا",
                        help_text="Physical address of the company - Arabic",
                        verbose_name="Address (Arabic)",
                    ),
                ),
                (
                    "google_maps_url",
                    models.URLField(
                        blank=True,
                        help_text="Google Maps embed or link URL",
                        max_length=500,
                        verbose_name="Google Maps URL",
                    ),
                ),
                (
                    "working_hours",
                    models.CharField(
                        blank=True,
                        default="Sunday - Thursday: 9:00 AM - 6:00 PM",
                        help_text="Business working hours - English",
                        max_length=200,
                        verbose_name="Working Hours (English)",
                    ),
                ),
                (
                    "working_hours_ar",
                    models.CharField(
                        blank=True,
                        default="الأحد - الخميس: 9:00 صباحاً - 6:00 مساءً",
                        help_text="Business working hours - Arabic",
                        max_length=200,
                        verbose_name="Working Hours (Arabic)",
                    ),
                ),
                (
                    "currency_code",
                    models.CharField(
                        default="SYP",
                        help_text="ISO currency code (e.g., SYP, USD)",
                        max_length=10,
                        verbose_name="Currency Code",
                    ),
                ),
                (
                    "currency_symbol",
                    models.CharField(
                        default="ل.س",
                        help_text="Currency symbol to display (e.g., ل.س, $)",
                        max_length=10,
                        verbose_name="Currency Symbol",
                    ),
                ),
                (
                    "currency_position",
                    models.CharField(
                        choices=[
                            ("before", "Before price ($ 100)"),
                            ("after", "After price (100 $)"),
                        ],
                        default="after",
                        help_text="Where to display the currency symbol",
                        max_length=10,
                        verbose_name="Currency Position",
                    ),
                ),
                (
                    "is_maintenance_mode",
                    models.BooleanField(
                        default=False,
                        help_text="Enable maintenance mode to show maintenance page to visitors",
                        verbose_name="Maintenance Mode",
                    ),
                ),
                (
                    "maintenance_message",
                    models.TextField(
                        blank=True,
                        default="We are currently performing maintenance. Please check back later.",
                        help_text="Message to display during maintenance - English",
                        verbose_name="Maintenance Message (English)",
                    ),
                ),
                (
                    "maintenance_message_ar",
                    models.TextField(
                        blank=True,
                        default="نقوم حالياً بأعمال الصيانة. يرجى المحاولة لاحقاً.",
                        help_text="Message to display during maintenance - Arabic",
                        verbose_name="Maintenance Message (Arabic)",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
            ],
            options={
                "verbose_name": "Site Settings",
                "verbose_name_plural": "Site Settings",
            },
        ),
        migrations.CreateModel(
            name="SocialLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "platform",
                    models.CharField(
                        choices=[
                            ("facebook", "Facebook"),
                            ("instagram", "Instagram"),
                            ("twitter", "Twitter / X"),
                            ("tiktok", "TikTok"),
                            ("youtube", "YouTube"),
                            ("linkedin", "LinkedIn"),
                            ("telegram", "Telegram"),
                            ("whatsapp", "WhatsApp"),
                            ("snapchat", "Snapchat"),
                            ("pinterest", "Pinterest"),
                            ("other", "Other"),
                        ],
                        help_text="Social media platform",
                        max_length=20,
                        verbose_name="Platform",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        help_text="Name to display (e.g., 'Follow us on Facebook')",
                        max_length=50,
                        verbose_name="Display Name",
                    ),
                ),
                (
                    "url",
                    models.URLField(
                        help_text="Full URL to the social media page/profile",
                        max_length=500,
                        verbose_name="URL",
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        blank=True,
                        help_text="Icon class name (e.g., 'fab fa-facebook') or emoji",
                        max_length=50,
                        verbose_name="Icon",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Order in which to display (lower = first)",
                        verbose_name="Display Order",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Show this link on the site",
                        verbose_name="Is Active",
                    ),
                ),
                (
                    "open_in_new_tab",
                    models.BooleanField(
                        default=True,
                        help_text="Open the link in a new browser tab",
                        verbose_name="Open in New Tab",
                    ),
                ),
            ],
            options={
                "verbose_name": "Social Link",
                "verbose_name_plural": "Social Links",
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="TrustSignal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        help_text="Icon class name or emoji (e.g., '🚚', 'fas fa-truck')",
                        max_length=50,
                        verbose_name="Icon",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Trust signal title - English",
                        max_length=100,
                        verbose_name="Title (English)",
                    ),
                ),
                (
                    "title_ar",
                    models.CharField(
                        help_text="Trust signal title - Arabic",
                        max_length=100,
                        verbose_name="Title (Arabic)",
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        help_text="Short description - English",
                        max_length=200,
                        verbose_name="Description (English)",
                    ),
                ),
                (
                    "description_ar",
                    models.CharField(
                        blank=True,
                        help_text="Short description - Arabic",
                        max_length=200,
                        verbose_name="Description (Arabic)",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Order in display (lower = first)",
                        verbose_name="Display Order",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Show this trust signal",
                        verbose_name="Is Active",
                    ),
                ),
            ],
            options={
                "verbose_name": "Trust Signal",
                "verbose_name_plural": "Trust Signals",
                "ordering": ["order", "title"],
            },
        ),
        migrations.CreateModel(
            name="NavigationItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        choices=[
                            ("header", "Header Menu"),
                            ("header_mobile", "Header Mobile Menu"),
                            ("footer_about", "Footer - About"),
                            ("footer_support", "Footer - Support"),
                            ("footer_legal", "Footer - Legal"),
                            ("sidebar", "Sidebar Menu"),
                        ],
                        help_text="Where to display this menu item",
                        max_length=20,
                        verbose_name="Location",
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        help_text="Menu item text - English",
                        max_length=100,
                        verbose_name="Label (English)",
                    ),
                ),
                (
                    "label_ar",
                    models.CharField(
                        help_text="Menu item text - Arabic",
                        max_length=100,
                        verbose_name="Label (Arabic)",
                    ),
                ),
                (
                    "url",
                    models.CharField(
                        help_text="Link URL (can be relative like '/products' or absolute)",
                        max_length=500,
                        verbose_name="URL",
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        blank=True,
                        help_text="Icon class name or emoji",
                        max_length=50,
                        verbose_name="Icon",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Order in menu (lower = first)",
                        verbose_name="Display Order",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Show this menu item",
                        verbose_name="Is Active",
                    ),
                ),
                (
                    "visibility",
                    models.CharField(
                        choices=[
                            ("all", "All Users"),
                            ("guest", "Guests Only"),
                            ("authenticated", "Logged In Users"),
                            ("customer", "Customers Only"),
                            ("vendor", "Vendors Only"),
                            ("admin", "Admins Only"),
                        ],
                        default="all",
                        help_text="Who can see this menu item",
                        max_length=20,
                        verbose_name="Visibility",
                    ),
                ),
                (
                    "open_in_new_tab",
                    models.BooleanField(
                        default=False,
                        help_text="Open link in a new browser tab",
                        verbose_name="Open in New Tab",
                    ),
                ),
                (
                    "highlight",
                    models.BooleanField(
                        default=False,
                        help_text="Highlight this item (e.g., for promotions)",
                        verbose_name="Highlight",
                    ),
                ),
                (
                    "highlight_color",
                    models.CharField(
                        blank=True,
                        help_text="Color for highlighted item (hex or color name)",
                        max_length=20,
                        verbose_name="Highlight Color",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        help_text="Parent menu item (for nested menus)",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="settings_app.navigationitem",
                        verbose_name="Parent Item",
                    ),
                ),
            ],
            options={
                "verbose_name": "Navigation Item",
                "verbose_name_plural": "Navigation Items",
                "ordering": ["location", "order", "label"],
            },
        ),
    ]
