# Generated by Django 5.0 on 2026-01-10 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_app', '0002_initial_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sociallink',
            name='url',
            field=models.URLField(blank=True, default='', help_text='Full URL to the social media page/profile', max_length=500, verbose_name='URL'),
        ),
    ]
