# Generated by Django 5.0 on 2025-12-25 11:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vendor',
            options={'ordering': ['name'], 'verbose_name': 'البائع / Vendor', 'verbose_name_plural': 'البائعون / Vendors'},
        ),
        migrations.AlterField(
            model_name='vendor',
            name='commission_rate',
            field=models.DecimalField(decimal_places=2, default=10.0, help_text='Commission percentage (0-100)', max_digits=5, verbose_name='نسبة العمولة / Commission Rate'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء / Created At'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='description',
            field=models.TextField(blank=True, verbose_name='الوصف / Description'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='نشط / Active'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='vendors/logos/', verbose_name='الشعار / Logo'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='name',
            field=models.CharField(help_text='اسم العلامة التجارية', max_length=100, unique=True, verbose_name='اسم البائع / Vendor Name'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='primary_color',
            field=models.CharField(default='#000000', help_text='Hex color code (e.g., #E91E63)', max_length=7, verbose_name='اللون الأساسي / Primary Color'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, unique=True, verbose_name='المعرف / Slug'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث / Updated At'),
        ),
        migrations.CreateModel(
            name='VendorApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applicant_name', models.CharField(max_length=100, verbose_name='اسم المتقدم / Applicant Name')),
                ('applicant_email', models.EmailField(max_length=254, verbose_name='البريد الإلكتروني / Email')),
                ('applicant_phone', models.CharField(max_length=20, verbose_name='رقم الهاتف / Phone')),
                ('store_name', models.CharField(help_text='اسم المتجر المقترح', max_length=100, verbose_name='اسم المتجر / Store Name')),
                ('store_description', models.TextField(blank=True, help_text='وصف مختصر عن المتجر والمنتجات', verbose_name='وصف المتجر / Store Description')),
                ('store_logo', models.ImageField(blank=True, null=True, upload_to='vendor_applications/logos/', verbose_name='شعار المتجر / Store Logo')),
                ('business_type', models.CharField(choices=[('individual', 'فردي / Individual'), ('company', 'شركة / Company'), ('brand', 'علامة تجارية / Brand'), ('other', 'أخرى / Other')], default='individual', max_length=20, verbose_name='نوع النشاط / Business Type')),
                ('business_address', models.TextField(blank=True, verbose_name='عنوان النشاط / Business Address')),
                ('business_license', models.FileField(blank=True, help_text='صورة رخصة النشاط التجاري (اختياري)', null=True, upload_to='vendor_applications/documents/', verbose_name='رخصة النشاط / Business License')),
                ('status', models.CharField(choices=[('pending', 'قيد المراجعة / Pending'), ('approved', 'مقبول / Approved'), ('rejected', 'مرفوض / Rejected')], db_index=True, default='pending', max_length=20, verbose_name='الحالة / Status')),
                ('admin_notes', models.TextField(blank=True, help_text='ملاحظات داخلية للأدمن', verbose_name='ملاحظات الأدمن / Admin Notes')),
                ('rejection_reason', models.TextField(blank=True, help_text='سبب الرفض (يُرسل للمتقدم)', verbose_name='سبب الرفض / Rejection Reason')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ المراجعة / Reviewed At')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ التقديم / Submitted At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث / Updated At')),
                ('created_vendor', models.OneToOneField(blank=True, help_text='البائع الذي تم إنشاؤه بعد الموافقة', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='application', to='vendors.vendor', verbose_name='البائع المُنشأ / Created Vendor')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_vendor_applications', to=settings.AUTH_USER_MODEL, verbose_name='تمت المراجعة بواسطة / Reviewed By')),
                ('user', models.ForeignKey(blank=True, help_text='المستخدم المرتبط (إذا كان مسجلاً)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendor_applications', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم / User')),
            ],
            options={
                'verbose_name': 'طلب انضمام بائع / Vendor Application',
                'verbose_name_plural': 'طلبات انضمام البائعين / Vendor Applications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='vendors_ven_status_f8ec29_idx'), models.Index(fields=['applicant_email'], name='vendors_ven_applica_3a1940_idx')],
            },
        ),
    ]
