# Generated by Django 5.0 on 2025-12-28 21:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vendors", "0002_alter_vendor_options_alter_vendor_commission_rate_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vendor",
            name="commission_rate",
            field=models.DecimalField(
                decimal_places=2,
                default=10.0,
                help_text="Commission percentage (0-100)",
                max_digits=5,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
                verbose_name="نسبة العمولة / Commission Rate",
            ),
        ),
        migrations.AddIndex(
            model_name="vendor",
            index=models.Index(
                fields=["is_active"], name="vendors_ven_is_acti_5c8a37_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="vendor",
            index=models.Index(fields=["slug"], name="vendors_ven_slug_6ed865_idx"),
        ),
    ]
