# Generated by Django 5.0 on 2025-12-30 15:54

import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0003_alter_vendor_commission_rate_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='primary_color',
            field=models.CharField(default='#000000', help_text='Hex color code (e.g., #E91E63)', max_length=7, validators=[django.core.validators.RegexValidator('^#[0-9A-Fa-f]{6}$', 'Invalid hex color')], verbose_name='اللون الأساسي / Primary Color'),
        ),
        migrations.AddConstraint(
            model_name='vendorapplication',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'pending'), ('user__isnull', False)), fields=('user',), name='uq_vendorapp_one_pending_per_user'),
        ),
        migrations.AddConstraint(
            model_name='vendorapplication',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('applicant_email',), name='uq_vendorapp_one_pending_per_email'),
        ),
        migrations.AddConstraint(
            model_name='vendorapplication',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('reviewed_at__isnull', True), ('reviewed_by__isnull', True), ('status', 'pending')), models.Q(('reviewed_at__isnull', False), ('reviewed_by__isnull', False), ('status__in', ['approved', 'rejected'])), _connector='OR'), name='ck_vendorapp_review_fields_consistent'),
        ),
    ]
