# Generated by Django 5.0 on 2026-01-02 13:21

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0004_alter_vendor_primary_color_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notify_new_orders', models.BooleanField(default=True, help_text='تلقي إشعارات عند استلام طلبات جديدة', verbose_name='إشعارات الطلبات الجديدة / Notify New Orders')),
                ('notify_order_status_changes', models.BooleanField(default=True, help_text='تلقي إشعارات عند تغيير حالة الطلب', verbose_name='إشعارات تغيير حالة الطلب / Notify Order Status Changes')),
                ('notify_order_cancellations', models.BooleanField(default=True, help_text='تلقي إشعارات عند إلغاء الطلبات', verbose_name='إشعارات إلغاء الطلبات / Notify Order Cancellations')),
                ('notify_low_stock', models.BooleanField(default=True, help_text='تلقي إشعارات عند انخفاض المخزون', verbose_name='إشعارات المخزون المنخفض / Notify Low Stock')),
                ('notify_out_of_stock', models.BooleanField(default=True, help_text='تلقي إشعارات عند نفاد المخزون', verbose_name='إشعارات نفاد المخزون / Notify Out of Stock')),
                ('notify_new_customers', models.BooleanField(default=False, help_text='تلقي إشعارات عند تسجيل زبائن جدد', verbose_name='إشعارات الزبائن الجدد / Notify New Customers')),
                ('email_notifications_enabled', models.BooleanField(default=True, help_text='تفعيل إرسال الإشعارات عبر البريد الإلكتروني', verbose_name='تفعيل إشعارات البريد الإلكتروني / Email Notifications Enabled')),
                ('auto_confirm_orders', models.BooleanField(default=False, help_text='تأكيد الطلبات الجديدة تلقائياً عند استلامها', verbose_name='تأكيد الطلبات تلقائياً / Auto Confirm Orders')),
                ('default_order_status', models.CharField(choices=[('pending', 'معلق / Pending'), ('confirmed', 'مؤكد / Confirmed'), ('processing', 'قيد المعالجة / Processing')], default='pending', help_text='الحالة الافتراضية للطلبات الجديدة', max_length=20, verbose_name='حالة الطلب الافتراضية / Default Order Status')),
                ('stock_alert_threshold', models.PositiveIntegerField(default=10, help_text='عدد الوحدات التي عندها يتم إرسال تنبيه المخزون المنخفض', validators=[django.core.validators.MinValueValidator(0)], verbose_name='حد تنبيه المخزون / Stock Alert Threshold')),
                ('auto_archive_orders_after_days', models.PositiveIntegerField(blank=True, help_text='عدد الأيام بعدها يتم أرشفة الطلبات تلقائياً (اتركه فارغاً لتعطيل الأرشفة التلقائية)', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(365)], verbose_name='أرشفة الطلبات تلقائياً بعد (أيام) / Auto Archive Orders After Days')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء / Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث / Updated At')),
                ('vendor', models.OneToOneField(help_text='البائع المرتبط بهذه الإعدادات', on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='vendors.vendor', verbose_name='البائع / Vendor')),
            ],
            options={
                'verbose_name': 'إعدادات البائع / Vendor Settings',
                'verbose_name_plural': 'إعدادات البائعين / Vendor Settings',
                'indexes': [models.Index(fields=['vendor'], name='vendors_ven_vendor__84bdda_idx')],
            },
        ),
    ]
