# Generated by Django 5.0 on 2025-12-20 23:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(help_text='Unique verification token.', max_length=100, unique=True, verbose_name='verification token')),
                ('is_verified', models.BooleanField(default=False, help_text='Whether the email has been verified.', verbose_name='is verified')),
                ('expires_at', models.DateTimeField(help_text='Token expiration date and time.', verbose_name='expires at')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(help_text='User to verify.', on_delete=django.db.models.deletion.CASCADE, related_name='email_verification', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'email verification',
                'verbose_name_plural': 'email verifications',
                'indexes': [models.Index(fields=['token'], name='users_email_token_c80ef6_idx'), models.Index(fields=['user', 'is_verified'], name='users_email_user_id_da7e8a_idx')],
            },
        ),
    ]
