# Generated by Django 5.0 on 2025-12-30 15:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_emailverification'),
        ('vendors', '0003_alter_vendor_commission_rate_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='vendoruser',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='vendoruser',
            name='vendor',
            field=models.ForeignKey(help_text='Vendor associated with this user.', on_delete=django.db.models.deletion.PROTECT, related_name='vendor_users', to='vendors.vendor'),
        ),
        migrations.AddIndex(
            model_name='emailverification',
            index=models.Index(fields=['expires_at'], name='users_email_expires_083d9c_idx'),
        ),
        migrations.AddConstraint(
            model_name='vendoruser',
            constraint=models.UniqueConstraint(fields=('user', 'vendor'), name='uq_vendoruser_user_vendor'),
        ),
        migrations.AddConstraint(
            model_name='vendoruser',
            constraint=models.UniqueConstraint(condition=models.Q(('is_owner', True)), fields=('vendor',), name='uq_vendor_one_owner'),
        ),
    ]
