# Generated by Django 5.0 on 2025-12-31 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_vendoruser_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('customer', 'Customer'), ('vendor', 'Vendor'), ('admin', 'Super Admin'), ('content_manager', 'Content Manager'), ('order_manager', 'Order Manager'), ('support', 'Support Staff')], default='customer', help_text='User role: Customer, Vendor, or Admin.', max_length=20, verbose_name='role'),
        ),
    ]
